# À n'utiliser qu'en développement local

apiVersion: v1
kind: ServiceAccount
metadata:
  name: gateway-sa
  namespace: default
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role  # Role limité au namespace, pas ClusterRole
metadata:
  name: spring-k8s-discovery-dev
  namespace: default
rules:
  - apiGroups: [""]
    resources: ["services", "endpoints", "pods"]
    verbs: ["get", "list"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: gateway-discovery-binding-dev
  namespace: default
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: spring-k8s-discovery-dev
subjects:
  - kind: ServiceAccount
    name: gateway-sa
    namespace: default
